account/urls.py
from django.urls import path

from .views import ( homeview, signupview, signup_completeview, loginview, logoutview, user_informationview, user_updateview, 
PasswordChange, PasswordChangeDone, 
)

urlpatterns = [
    path('home/', homeview, name='home'),
    path('signup/', signupview, name='signup'),
    path('signup-complete/', signup_completeview, name='signup_complete'),
    path('login/', loginview, name='login'),
    path('logout/', logoutview, name='logout'),
    path('user-information/<int:pk>/', user_informationview, name='user_information'),
    path('user-update/<int:pk>/', user_updateview, name='user_update'),
    path('password-change/<int:pk>/', PasswordChange.as_view(), name='password_change'),
    path('password-change-complete/', PasswordChangeDone.as_view(), name='password_change_complete'),
]

contents/urls.py
from django.urls import path

from .views import ( 
    item_type_CreateView, item_type_CreateCompleteView, item_color_CreateView, item_color_CreateCompleteView, item_brand_CreateView, item_brand_CreateCompleteView,
    purchase_place_CreateView, purchase_place_CreateCompleteView, closet_CreateView, closet_CreateCompleteView, item_Createview, item_CreateCompleteView, item_category_GateView,
    item_ListView, item_DetailView, item_DeleteView, item_Delete_CompleteView, item_type_DeleteView, item_type_Delete_CompleteView, item_color_DeleteView, item_color_Delete_CompleteView,
    item_brand_DeleteView, item_brand_Delete_CompleteView, purchase_place_DeleteView, purchase_place_Delete_CompleteView, closet_DeleteView, closet_Delete_CompleteView,
    closet_DeleteView, closet_Delete_CompleteView, item_type_UpdateView, item_type_UpdateCompleteView, item_color_UpdateView, item_color_UpdateCompleteView,
    item_brand_UpdateView, item_brand_UpdateCompleteView, purchase_place_UpdateView, purchase_place_UpdateCompleteView, closet_UpdateView, closet_UpdateCompleteView,
    item_Updateview, item_Update_CompleteView, closet_ListView
)

urlpatterns = [
    path('item-category-gate/', item_category_GateView, name='item_category_gate'),
    path('item-type-create/', item_type_CreateView, name='item_type_create'),
    path('item-type-create-complete/', item_type_CreateCompleteView, name='item_type_create_complete'),
    path('item-type-update/<int:pk>/', item_type_UpdateView, name='item_type_update'),
    path('item-type-update-complete/', item_type_UpdateCompleteView, name='item_type_update_complete'),
    path('item-type-delete/<int:pk>/', item_type_DeleteView, name='item_type_delete'),
    path('item-type-delete-complete/', item_type_Delete_CompleteView, name='item_type_delete_complete'),
    path('item-color-create/', item_color_CreateView, name='item_color_create'),
    path('item-color-create-complete/', item_color_CreateCompleteView, name='item_color_create_complete'),
    path('item-color-update/<int:pk>/', item_color_UpdateView, name='item_color_update'),
    path('item-color-update-complete/', item_color_UpdateCompleteView, name='item_color_update_complete'),
    path('item-color-delete/<int:pk>/', item_color_DeleteView, name='item_color_delete'),
    path('item-color-delete-complete/', item_color_Delete_CompleteView, name='item_color_delete_complete'),
    path('item-brand-create/', item_brand_CreateView, name='item_brand_create'),
    path('item-brand-create-complete/', item_brand_CreateCompleteView, name='item_brand_create_complete'),
    path('item-brand-update/<int:pk>/', item_brand_UpdateView, name='item_brand_update'),
    path('item-brand-update-complete/', item_brand_UpdateCompleteView, name='item_brand_update_complete'),
    path('item-brand-delete/<int:pk>/', item_brand_DeleteView, name='item_brand_delete'),
    path('item-brand-delete-complete/', item_brand_Delete_CompleteView, name='item_brand_delete_complete'),
    path('purchase-place-create/', purchase_place_CreateView, name='purchase_place_create'),
    path('purchase-place-create-complete/', purchase_place_CreateCompleteView, name='purchase_place_create_complete'),
    path('purchase-place-update/<int:pk>/', purchase_place_UpdateView, name='purchase_place_update'),
    path('purchase-place-update-complete/', purchase_place_UpdateCompleteView, name='purchase_place_update_complete'),
    path('purchase-place-delete/<int:pk>/', purchase_place_DeleteView, name='purchase_place_delete'),
    path('purchase-place-delete-complete/', purchase_place_Delete_CompleteView, name='purchase_place_delete_complete'),
    path('closet-create/', closet_CreateView, name='closet_create'),
    path('closet-create-complete/', closet_CreateCompleteView, name='closet_create_complete'),
    path('closet-update/<int:pk>/', closet_UpdateView, name='closet_update'),
    path('closet-update-complete/', closet_UpdateCompleteView, name='closet_update_complete'),
    path('closet-delete/<int:pk>/', closet_DeleteView, name='closet_delete'),
    path('closet-delete-complete/', closet_Delete_CompleteView, name='closet_delete_complete'),
    path('item-create/', item_Createview, name='item_create'),
    path('item-create-complete/', item_CreateCompleteView, name='item_create_complete'),
    path('item-update/<int:pk>/', item_Updateview, name='item_update'),
    path('item-update-complete/', item_Update_CompleteView, name='item_update_complete'),
    path('item-list/', item_ListView, name='item_list'),
    path('item-detail/<int:pk>/', item_DetailView, name='item_detail'),
    path('item-delete/<int:pk>/', item_DeleteView, name='item_delete'),
    path('item-delete-complete/', item_Delete_CompleteView, name='item_delete_complete'),
    path('closet-list/', closet_ListView, name='closet_list'),
]

yourtansuu3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from account.views import topview

urlpatterns = [
    path('', topview, name="top"),
    path('account/', include('account.urls')),
    path('contents/', include('contents.urls')),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contents/models.py
import datetime
from django.db import models
from django.conf import settings


SEASON_CHOICES = [('spring','春'),('summer','夏'),('fall','秋'),('winter','冬')]
OCCASION_CHOICES = [('daily_use','普段着'),('work_wear','仕事'),('active_wear','よそ行き'),('sports_wear','スポーツ'),('other_use','その他')]
FAVORITE_LEVEL_CHOICES = [(1,'めちゃ低い'),(2,'低い'),(3,'普通'),(4,'高い'),(5,'めちゃ高い')]
ITEM_IMPORTANCE_CHOICES = [(1,'捨てれる'),(2,'悩む'),(3,'普通'),(4,'まあ大事'),(5,'めっちゃ大事')]


class Closet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    closet_name = models.CharField(verbose_name='クローゼット名', max_length=255, unique=True)

    class Meta:
        ordering =['closet_name']
    
    def __str__(self):
        return self.closet_name
    
    @property
    def item_count(self):
        item_count= Item.objects.filter(closet=self).count()
        return item_count


class ItemType(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    item_type = models.CharField(verbose_name='アイテム種類', max_length=255, unique=True)

    def __str__(self):
        return self.item_type

class ItemColor(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    item_color = models.CharField(verbose_name='アイテムカラー', max_length=255, unique=True)

    def __str__(self):
        return self.item_color

class ItemBrand(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    item_brand = models.CharField(verbose_name='ブランド', max_length=255, unique=True)

    def __str__(self):
        return self.item_brand

class PurchasePlace(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    purchase_place = models.CharField(verbose_name='購入場所', max_length=255, unique=True)

    def __str__(self):
        return self.purchase_place


class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE,null=True)
    item_type = models.ForeignKey(ItemType, on_delete=models.SET_NULL, blank=True, null=True, default=None)
    item_color = models.ForeignKey(ItemColor, on_delete=models.SET_NULL, blank=True, null=True, default=None)
    item_brand = models.ForeignKey(ItemBrand, on_delete=models.SET_NULL, blank=True, null=True, default=None)
    purchase_place = models.ForeignKey(PurchasePlace, on_delete=models.SET_NULL, blank=True, null=True, default=None)
    closet = models.ForeignKey(Closet, on_delete=models.PROTECT, blank=True, null=True, default=None)
    season = models.CharField(verbose_name = '季節', max_length=10, choices = SEASON_CHOICES, default='spring')
    occasion = models.CharField(verbose_name = 'シーン', max_length=30, choices = OCCASION_CHOICES, default='daily_use')
    item_name = models.CharField(verbose_name = 'アイテム名称', max_length=300, unique=True)
    purchase_date = models.DateTimeField(verbose_name = '購入日', blank=True, null=True)
    pricing = models.IntegerField(verbose_name = '購入価格(円)', )
    item_image = models.ImageField(verbose_name = 'アイテム画像', upload_to='contents/item_images', blank = True, null=True)
    memo = models.TextField(verbose_name = 'メモ', blank=True, null=True)
    favorite_level = models.IntegerField(verbose_name = 'お気に入り度', choices = FAVORITE_LEVEL_CHOICES, default=None, blank=True, null=True)
    item_importance = models.IntegerField(verbose_name = '大事さ', choices = ITEM_IMPORTANCE_CHOICES, default=None, blank=True, null=True)
    create_date = models.DateTimeField(verbose_name = '作成日', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name = '更新日', auto_now=True)
    

    class Meta:
        ordering = ['create_date']
    
    def __str__(self):
        return self.item_name
    
    @property
    def closet_count(self):
        closet_count = Closet.objetcs.filter(closet_name=self).count()
        return closet_count

contents/forms.py
from django import forms
from django.conf import settings

from .models import (Item, Closet, ItemType, ItemColor, ItemBrand, PurchasePlace, SEASON_CHOICES, OCCASION_CHOICES, ITEM_IMPORTANCE_CHOICES, FAVORITE_LEVEL_CHOICES)

MONTHS = {
    1: '1月', 2: '2月', 3: '3月', 4: '4月',
    5: '5月', 6: '6月', 7: '7月', 8: '8月',
    9: '9月', 10: '10月', 11: '11月', 12: '12月'
}


class ItemTypeCreateForm(forms.ModelForm):

    class Meta:
        model = ItemType
        fields = ('item_type',)
        labels = {'item_type':'アイテム種類'}
    
    def clean_item_type(self):
        item_type = self.cleaned_data['item_type']
        if item_type:
            item_type_number = ItemType.objects.filter(item_type=item_type).count()
            if item_type_number > settings.ITEM_TYPE_MAX:
                self.add_error('item_type',f"アイテム種類に設定出来る件数は{settings.ITEM_TYPE_MAX}件までです。")
        return item_type


class ItemColorCreateForm(forms.ModelForm):

    class Meta:
        model = ItemColor
        fields = ('item_color',)
        labels = {'item_color':'アイテムカラー'}
    
    def clean_item_color(self):
        item_color = self.cleaned_data['item_color']
        if item_color:
            item_color_number = ItemColor.objects.filter(item_color=item_color).count()
            if item_color_number > settings.ITEM_COLOR_MAX:
                self.add_error('item_color',f"アイテムカラーに設定出来る件数は{settings.ITEM_COLOR_MAX}件までです。")
        return item_color


class ItemBrandCreateForm(forms.ModelForm):

    class Meta:
        model = ItemBrand
        fields = ('item_brand',)
        labels = {'item_brand':'ブランド名'}
    
    def clean_item_brand(self):
        item_brand = self.cleaned_data['item_brand']
        if item_brand:
            item_brand_number = ItemBrand.objects.filter(item_brand=item_brand).count()
            if item_brand_number > settings.ITEM_BRAND_MAX:
                self.add_error('item_brand',f"ブランドに設定出来る件数は{settings.ITEM_BRAND_MAX}件までです。")
        return item_brand


class PurchasePlaceCreateForm(forms.ModelForm):

    class Meta:
        model = PurchasePlace
        fields = ('purchase_place',)
        labels = {'purchase_place':'購入場所'}
    
    def clean_purchase_place(self):
        purchase_place = self.cleaned_data['purchase_place']
        if purchase_place:
            purchase_place_number = PurchasePlace.objects.filter(purchase_place=purchase_place).count()
            if purchase_place_number > settings.PURCHASE_PLACE_MAX:
                self.add_error('purchase_place',f"購入場所に設定出来る件数は{settings.PURCHASE_PLACE_MAX}件までです。")
        return purchase_place


class ClosetCreateForm(forms.ModelForm):

    class Meta:
        model = Closet
        fields = ('closet_name',)
        labels = {'closet_name':'クローゼット名'}
    
    def clean_closet_name(self):
        closet_name = self.cleaned_data['closet_name']
        if closet_name:
            closet_name_number = Closet.objects.filter(closet_name=closet_name).count()
            if closet_name_number > settings.CLOSET_NAME_MAX:
                self.add_error('closet_name',f"開設できるクローゼットは{settings.CLOSET_NAME_MAX}です。")
        return closet_name


class ItemCreateForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = ('item_name','purchase_date', 'pricing', 'season','occasion', 'item_image','favorite_level', 'item_importance','closet', 'item_type','item_color','item_brand',
        'purchase_place', 'memo',)

        labels = {'item_name':'アイテム名称','item_type':'アイテム種類','season':'季節','occasion':'シーン','pricing':'購入価格(円)','purchase_date':'購入日','closet':'クローゼット',
        'item_color':'アイテムカラー','item_brand':'ブランド','purchase_place':'購入場所','item_image':'アイテム画像','favorite_level':'お気に入り度','item_importance':'大事さ','memo':'メモ',}

        widgets = {
            'season': forms.RadioSelect(choices=SEASON_CHOICES),
            'occasion': forms.RadioSelect(choices=OCCASION_CHOICES),
            'purchase_date': forms.SelectDateWidget(years = [x for x in range(2000,2040)], months = MONTHS),
        }

templates/contents/item_list/item_detail.html
{% extends 'contents/contents_base.html' %}
{% load static django_bootstrap5 humanize %}


{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="card-title fs-3 fw-bolder">{{ object_item.item_name }}</div>
        </div>
        <div class="card-body p-9">
        <div class="row mb-5">
            <div class="col-xl-3">
                <div class="fs-6 fw-bold mt-2 mb-3">アイテム画像</div>
                    {% if object_item.item_image %}
                    <img src="{{ object_item.item_image.url }}" style="max-width: 300px;" alt="アイテム画像表示エラー"/>
                    {{ object_item.item_image.value }}
                    {% else %}
                    <img src="{% static 'static_images/Blank_image.jpeg' %}" class="figure-img img-fluid rounded text_center" style="max-width: 300px;">
                    {% endif %}
            </div>
            <div class="row mb-2">
                <div class="col-xl-3">
                    <p class="fs-6 fw-bold mt-2 mb-3">アイテム種類</p>
                    <p class="form-control form-control-solid">{{ object_item.item_type }}</p>
                </div>
                <div class="col-xl-3">
                    <p class="fs-6 fw-bold mt-2 mb-3">季節</p>
                    <p class="form-control form-control-solid">{{ object_item.get_season_display }}</p>
                </div>
                <div class="col-xl-3">
                    <p class="fs-6 fw-bold mt-2 mb-3">シーン</p>
                    <p class="form-control form-control-solid">{{ object_item.get_occasion_display }}</p>
                </div>
                <div class="col-xl-3">
                    <p class="fs-6 fw-bold mt-2 mb-3">アイテムカラー</p>
                    <p class="form-control form-control-solid">{{ object_item.item_color }}</p>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-xl-3">
                    <p class="fs-6 fw-bold mt-2 mb-3">ブランド</p>
                    <p class="form-control form-control-solid">{{ object_item.item_brand }}</p>
                </div>
                <div class="col-xl-3">
                    <p class="fs-6 fw-bold mt-2 mb-3">購入場所</p>
                    <p class="form-control form-control-solid">{{ object_item.purchase_place }}</p>
                </div>
                <div class="col-xl-3">
                    <p class="fs-6 fw-bold mt-2 mb-3">購入日</p>
                    <p class="form-control form-control-solid">{{ object_item.purchase_date | date:"Y年m月d日(D)" }}</p>
                </div>
                <div class="col-xl-3">
                    <p class="fs-6 fw-bold mt-2 mb-3">購入価格</p>
                    <p class="form-control form-control-solid">{{ object_item.pricing | intcomma}}円</p>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-xl-6">
                    <p class="fs-6 fw-bold mt-2 mb-3">お気に入り度</p>
                    <p class="form-control form-control-solid">{{ object_item.get_favorite_level_display }}</p>
                </div>
                <div class="col-xl-6">
                    <p class="fs-6 fw-bold mt-2 mb-3">大事さ</p>
                    <p class="form-control form-control-solid">{{ object_item.get_item_importance_display }}</p>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-xl-12">
                    <p class="fs-6 fw-bold mt-2 mb-3">メモ</p>
                    <p class="form-control form-control-solid">{{ object_item.memo }}</p>
                </div>
            </div> 
            <div class="row mb-2" style="text-align: center;">
                <div class="col-xl-4">
                    <a href="{% url 'item_list' %}" type="submit" class="btn btn-primary">一覧に戻る</a>
                </div>
                <div class="col-xl-4">
                    <a href="{% url 'item_update' object_item.pk %}" type="submit" class="btn btn-primary">アイテムを編集する</a>
                </div>
                <div class="col-xl-4">
                    <a href="{% url 'item_delete' object_item.pk %}" type="submit" class="btn btn-danger">アイテムを削除する</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/contents/item_list/item_list.html
{% extends 'contents/contents_base.html' %}
{% load static django_bootstrap5 humanize %}

{% block content %}
<div class="container">
    <h1>登録アイテム一覧</h1>
    <h7>登録アイテム総数：{{ paginator.count }}件</h7><br>
    <h7>今日は{{ today | date:"Y年m月d日(D)" }}です</h7>
    {% if page_object %}
    <table class="table table-rounded table-striped border gy-3 gs-3">
        <thead>
            <tr class="fw-bold fs-6 text-gray-800 border-bottom border-gray-200">
                <th class="min-w-10px">No.</th>
                <th class="min-w-10px">アイテム名称</th>
                <th class="min-w-10px">種類</th>
                <th class="min-w-10px">シーン</th>
                <th class="min-w-10px">カラー</th>
                <th class="min-w-10px">購入日</th>
                <th class="min-w-10px">購入価格</th>
                <th class="min-w-10px">詳細ページ</th>
            </tr>
        </thead>
        <tbody>
            {% for field in page_object %}
            <tr>
                <td>{{ forloop.counter0 | add:page_object.start_index }}</td>
                <td>{{ field.item_name }}</td>
                <td>{{ field.item_type }}</td>
                <td>{{ field.get_occasion_display }}</td>
                <td>{{ field.item_color }}</td>
                <td>{{ field.purchase_date| date:"Y年m月d日(D)" }}</td>
                <td>{{ field.pricing | intcomma }}円</td>
                <td><a href="{% url 'item_detail' field.pk %}"button class="btn btn-sm btn-primary" type="submit">詳細ページへ</a></td>
            </tr>
            {% endfor %}
        </tbody>
        {% else %}
        <p>まだアイテムが登録されていません</p>
        {% endif %}
    </table>
    <div class="pagination">
        <span class="step-links">
          {% if page_object.has_previous %}
          <a href="?page=1">&laquo; 1ページ目に戻る</a>
          <a href="?page={{ page_object.previous_page_number }}">前のページ</a>
          {% endif %}
          
          <span class="current">
            ページ {{ page_object.number }} / {{ page_object.paginator.num_pages }}
          </span>
          {% if page_object.has_next %}
          <a href="?page={{ page_object.next_page_number }}">次のページ</a>
          <a href="?page={{ page_object.paginator.num_pages }}">最後のページ &raquo;</a>
          {% endif %}
        </span>
    </div>
</div>
{% endblock content%}