account/urls.py
from django.urls import path

from .views import ( homeview, signupview, signup_completeview, loginview, logoutview, user_informationview, user_updateview, 
PasswordChange, PasswordChangeDone, 
)

urlpatterns = [
    path('home/', homeview, name='home'),
    path('signup/', signupview, name='signup'),
    path('signup-complete/', signup_completeview, name='signup_complete'),
    path('login/', loginview, name='login'),
    path('logout/', logoutview, name='logout'),
    path('user-information/<int:pk>/', user_informationview, name='user_information'),
    path('user-update/<int:pk>/', user_updateview, name='user_update'),
    path('password-change/<int:pk>/', PasswordChange.as_view(), name='password_change'),
    path('password-change-complete/', PasswordChangeDone.as_view(), name='password_change_complete'),
]

contents/urls.py
from django.urls import path

from .views import ( 
    item_type_CreateView, item_type_CreateCompleteView, item_color_CreateView, item_color_CreateCompleteView, item_brand_CreateView, item_brand_CreateCompleteView,
    purchase_place_CreateView, purchase_place_CreateCompleteView, closet_CreateView, closet_CreateCompleteView, item_Createview, item_CreateCompleteView, item_category_GateView,
    item_ListView, item_DetailView, item_DeleteView, item_Delete_CompleteView, item_type_DeleteView, item_type_Delete_CompleteView, item_color_DeleteView, item_color_Delete_CompleteView,
    item_brand_DeleteView, item_brand_Delete_CompleteView, purchase_place_DeleteView, purchase_place_Delete_CompleteView, closet_DeleteView, closet_Delete_CompleteView,
    closet_DeleteView, closet_Delete_CompleteView, item_type_UpdateView, item_type_UpdateCompleteView, item_color_UpdateView, item_color_UpdateCompleteView,
    item_brand_UpdateView, item_brand_UpdateCompleteView, purchase_place_UpdateView, purchase_place_UpdateCompleteView, closet_UpdateView, closet_UpdateCompleteView,
    item_Updateview, item_Update_CompleteView, closet_ListView
)

urlpatterns = [
    path('item-category-gate/', item_category_GateView, name='item_category_gate'),
    path('item-type-create/', item_type_CreateView, name='item_type_create'),
    path('item-type-create-complete/', item_type_CreateCompleteView, name='item_type_create_complete'),
    path('item-type-update/<int:pk>/', item_type_UpdateView, name='item_type_update'),
    path('item-type-update-complete/', item_type_UpdateCompleteView, name='item_type_update_complete'),
    path('item-type-delete/<int:pk>/', item_type_DeleteView, name='item_type_delete'),
    path('item-type-delete-complete/', item_type_Delete_CompleteView, name='item_type_delete_complete'),
    path('item-color-create/', item_color_CreateView, name='item_color_create'),
    path('item-color-create-complete/', item_color_CreateCompleteView, name='item_color_create_complete'),
    path('item-color-update/<int:pk>/', item_color_UpdateView, name='item_color_update'),
    path('item-color-update-complete/', item_color_UpdateCompleteView, name='item_color_update_complete'),
    path('item-color-delete/<int:pk>/', item_color_DeleteView, name='item_color_delete'),
    path('item-color-delete-complete/', item_color_Delete_CompleteView, name='item_color_delete_complete'),
    path('item-brand-create/', item_brand_CreateView, name='item_brand_create'),
    path('item-brand-create-complete/', item_brand_CreateCompleteView, name='item_brand_create_complete'),
    path('item-brand-update/<int:pk>/', item_brand_UpdateView, name='item_brand_update'),
    path('item-brand-update-complete/', item_brand_UpdateCompleteView, name='item_brand_update_complete'),
    path('item-brand-delete/<int:pk>/', item_brand_DeleteView, name='item_brand_delete'),
    path('item-brand-delete-complete/', item_brand_Delete_CompleteView, name='item_brand_delete_complete'),
    path('purchase-place-create/', purchase_place_CreateView, name='purchase_place_create'),
    path('purchase-place-create-complete/', purchase_place_CreateCompleteView, name='purchase_place_create_complete'),
    path('purchase-place-update/<int:pk>/', purchase_place_UpdateView, name='purchase_place_update'),
    path('purchase-place-update-complete/', purchase_place_UpdateCompleteView, name='purchase_place_update_complete'),
    path('purchase-place-delete/<int:pk>/', purchase_place_DeleteView, name='purchase_place_delete'),
    path('purchase-place-delete-complete/', purchase_place_Delete_CompleteView, name='purchase_place_delete_complete'),
    path('closet-create/', closet_CreateView, name='closet_create'),
    path('closet-create-complete/', closet_CreateCompleteView, name='closet_create_complete'),
    path('closet-update/<int:pk>/', closet_UpdateView, name='closet_update'),
    path('closet-update-complete/', closet_UpdateCompleteView, name='closet_update_complete'),
    path('closet-delete/<int:pk>/', closet_DeleteView, name='closet_delete'),
    path('closet-delete-complete/', closet_Delete_CompleteView, name='closet_delete_complete'),
    path('item-create/', item_Createview, name='item_create'),
    path('item-create-complete/', item_CreateCompleteView, name='item_create_complete'),
    path('item-update/<int:pk>/', item_Updateview, name='item_update'),
    path('item-update-complete/', item_Update_CompleteView, name='item_update_complete'),
    path('item-list/', item_ListView, name='item_list'),
    path('item-detail/<int:pk>/', item_DetailView, name='item_detail'),
    path('item-delete/<int:pk>/', item_DeleteView, name='item_delete'),
    path('item-delete-complete/', item_Delete_CompleteView, name='item_delete_complete'),
    path('closet-list/', closet_ListView, name='closet_list'),
]

yourtansuu3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from account.views import topview

urlpatterns = [
    path('', topview, name="top"),
    path('account/', include('account.urls')),
    path('contents/', include('contents.urls')),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contents/models.py
import datetime
from django.db import models
from django.conf import settings


SEASON_CHOICES = [('spring','春'),('summer','夏'),('fall','秋'),('winter','冬')]
OCCASION_CHOICES = [('daily_use','普段着'),('work_wear','仕事'),('active_wear','よそ行き'),('sports_wear','スポーツ'),('other_use','その他')]
FAVORITE_LEVEL_CHOICES = [(1,'めちゃ低い'),(2,'低い'),(3,'普通'),(4,'高い'),(5,'めちゃ高い')]
ITEM_IMPORTANCE_CHOICES = [(1,'捨てれる'),(2,'悩む'),(3,'普通'),(4,'まあ大事'),(5,'めっちゃ大事')]


class Closet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    closet_name = models.CharField(verbose_name='クローゼット名', max_length=255, unique=True)

    class Meta:
        ordering =['closet_name']
    
    def __str__(self):
        return self.closet_name
    
    @property
    def item_count(self):
        item_count= Item.objects.filter(closet=self).count()
        return item_count


class ItemType(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    item_type = models.CharField(verbose_name='アイテム種類', max_length=255, unique=True)

    def __str__(self):
        return self.item_type

class ItemColor(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    item_color = models.CharField(verbose_name='アイテムカラー', max_length=255, unique=True)

    def __str__(self):
        return self.item_color

class ItemBrand(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    item_brand = models.CharField(verbose_name='ブランド', max_length=255, unique=True)

    def __str__(self):
        return self.item_brand

class PurchasePlace(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE, null=True)
    create_date = models.DateTimeField(verbose_name='作成日', auto_now_add=True)
    purchase_place = models.CharField(verbose_name='購入場所', max_length=255, unique=True)

    def __str__(self):
        return self.purchase_place


class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE,null=True)
    item_type = models.ForeignKey(ItemType, on_delete=models.SET_NULL, blank=True, null=True, default=None)
    item_color = models.ForeignKey(ItemColor, on_delete=models.SET_NULL, blank=True, null=True, default=None)
    item_brand = models.ForeignKey(ItemBrand, on_delete=models.SET_NULL, blank=True, null=True, default=None)
    purchase_place = models.ForeignKey(PurchasePlace, on_delete=models.SET_NULL, blank=True, null=True, default=None)
    closet = models.ForeignKey(Closet, on_delete=models.PROTECT, blank=True, null=True, default=None)
    season = models.CharField(verbose_name = '季節', max_length=10, choices = SEASON_CHOICES, default='spring')
    occasion = models.CharField(verbose_name = 'シーン', max_length=30, choices = OCCASION_CHOICES, default='daily_use')
    item_name = models.CharField(verbose_name = 'アイテム名称', max_length=300, unique=True)
    purchase_date = models.DateTimeField(verbose_name = '購入日', blank=True, null=True)
    pricing = models.IntegerField(verbose_name = '購入価格(円)', )
    item_image = models.ImageField(verbose_name = 'アイテム画像', upload_to='contents/item_images', blank = True, null=True)
    memo = models.TextField(verbose_name = 'メモ', blank=True, null=True)
    favorite_level = models.IntegerField(verbose_name = 'お気に入り度', choices = FAVORITE_LEVEL_CHOICES, default=None, blank=True, null=True)
    item_importance = models.IntegerField(verbose_name = '大事さ', choices = ITEM_IMPORTANCE_CHOICES, default=None, blank=True, null=True)
    create_date = models.DateTimeField(verbose_name = '作成日', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name = '更新日', auto_now=True)
    

    class Meta:
        ordering = ['create_date']
    
    def __str__(self):
        return self.item_name
    
    @property
    def closet_count(self):
        closet_count = Closet.objetcs.filter(closet_name=self).count()
        return closet_count

contents/forms.py
from django import forms
from django.conf import settings

from .models import (Item, Closet, ItemType, ItemColor, ItemBrand, PurchasePlace, SEASON_CHOICES, OCCASION_CHOICES, ITEM_IMPORTANCE_CHOICES, FAVORITE_LEVEL_CHOICES)

MONTHS = {
    1: '1月', 2: '2月', 3: '3月', 4: '4月',
    5: '5月', 6: '6月', 7: '7月', 8: '8月',
    9: '9月', 10: '10月', 11: '11月', 12: '12月'
}


class ItemTypeCreateForm(forms.ModelForm):

    class Meta:
        model = ItemType
        fields = ('item_type',)
        labels = {'item_type':'アイテム種類'}
    
    def clean_item_type(self):
        item_type = self.cleaned_data['item_type']
        if item_type:
            item_type_number = ItemType.objects.filter(item_type=item_type).count()
            if item_type_number > settings.ITEM_TYPE_MAX:
                self.add_error('item_type',f"アイテム種類に設定出来る件数は{settings.ITEM_TYPE_MAX}件までです。")
        return item_type


class ItemColorCreateForm(forms.ModelForm):

    class Meta:
        model = ItemColor
        fields = ('item_color',)
        labels = {'item_color':'アイテムカラー'}
    
    def clean_item_color(self):
        item_color = self.cleaned_data['item_color']
        if item_color:
            item_color_number = ItemColor.objects.filter(item_color=item_color).count()
            if item_color_number > settings.ITEM_COLOR_MAX:
                self.add_error('item_color',f"アイテムカラーに設定出来る件数は{settings.ITEM_COLOR_MAX}件までです。")
        return item_color


class ItemBrandCreateForm(forms.ModelForm):

    class Meta:
        model = ItemBrand
        fields = ('item_brand',)
        labels = {'item_brand':'ブランド名'}
    
    def clean_item_brand(self):
        item_brand = self.cleaned_data['item_brand']
        if item_brand:
            item_brand_number = ItemBrand.objects.filter(item_brand=item_brand).count()
            if item_brand_number > settings.ITEM_BRAND_MAX:
                self.add_error('item_brand',f"ブランドに設定出来る件数は{settings.ITEM_BRAND_MAX}件までです。")
        return item_brand


class PurchasePlaceCreateForm(forms.ModelForm):

    class Meta:
        model = PurchasePlace
        fields = ('purchase_place',)
        labels = {'purchase_place':'購入場所'}
    
    def clean_purchase_place(self):
        purchase_place = self.cleaned_data['purchase_place']
        if purchase_place:
            purchase_place_number = PurchasePlace.objects.filter(purchase_place=purchase_place).count()
            if purchase_place_number > settings.PURCHASE_PLACE_MAX:
                self.add_error('purchase_place',f"購入場所に設定出来る件数は{settings.PURCHASE_PLACE_MAX}件までです。")
        return purchase_place


class ClosetCreateForm(forms.ModelForm):

    class Meta:
        model = Closet
        fields = ('closet_name',)
        labels = {'closet_name':'クローゼット名'}
    
    def clean_closet_name(self):
        closet_name = self.cleaned_data['closet_name']
        if closet_name:
            closet_name_number = Closet.objects.filter(closet_name=closet_name).count()
            if closet_name_number > settings.CLOSET_NAME_MAX:
                self.add_error('closet_name',f"開設できるクローゼットは{settings.CLOSET_NAME_MAX}です。")
        return closet_name


class ItemCreateForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = ('item_name','purchase_date', 'pricing', 'season','occasion', 'item_image','favorite_level', 'item_importance','closet', 'item_type','item_color','item_brand',
        'purchase_place', 'memo',)

        labels = {'item_name':'アイテム名称','item_type':'アイテム種類','season':'季節','occasion':'シーン','pricing':'購入価格(円)','purchase_date':'購入日','closet':'クローゼット',
        'item_color':'アイテムカラー','item_brand':'ブランド','purchase_place':'購入場所','item_image':'アイテム画像','favorite_level':'お気に入り度','item_importance':'大事さ','memo':'メモ',}

        widgets = {
            'season': forms.RadioSelect(choices=SEASON_CHOICES),
            'occasion': forms.RadioSelect(choices=OCCASION_CHOICES),
            'purchase_date': forms.SelectDateWidget(years = [x for x in range(2000,2040)], months = MONTHS),
        }

templates/contents/item_edit/item_delete.html
{% extends 'contents/contents_base.html' %}
{% load static django_bootstrap5 humanize %}

{% block content %}
<div class="container">
    <legend class="text_center space_top">以下のアイテムを削除しますか？</legend>
    <form action='' method="POST">{% csrf_token %}
        {% for item in object_item %}
        <ul>
            <li>アイテム種類：{{ item.get_item_type_display }}</li>
            <li>季節：{{ item.get_season_display }}</li>
            <li class="table-light">シーン：{{ item.get_occasion_display }}</li>
            <li class="table-light">アイテム名称：{{ item.item_name }}</li>
            <li class="table-light">アイテムカラー：{{ item.get_item_color_display }}</li>
            <li class="table-light">ブランド：{{ item.item_brand }}</li>
            <li class="table-light">購入日：{{ item.purchase_date }}</li>
            <li class="table-light">購入価格：{{ item.pricing }}</li>
            <li class="table-light">購入場所：{{ item.purchase_place }}</li>
            <li class="">メモ：{{ item.memo }}</li>
            <li class="table-light">お気に入り度：{{ item.get_favorite_level_display }}</li>
            <li class="table-light">大事さ：{{ item.get_favorite_level_display }}</li>
            </ul>
        {% endfor %}
        <button type = "submit" name = "button"  value = "confirm">削除します</button>
    </form>
<a href="{% url 'home' %}" class="btn btn-md btn-info">ホームに戻る</a>
</div>
{% endblock content %}

templates/contents/item_edit/item_delete_complete.html
{% extends 'contents/contents_base.html' %}
{% load static django_bootstrap5 humanize %}

{% block content %}
<div class="container">
    <form action='' method="POST">
        {% csrf_token %}
        <legend class="text_center space_top">指定したアイテムを削除しました。</legend>
    </form>
    <a href="{% url 'item_list' %}" class="btn btn-md btn-primary space_bottom" type="submit">アイテム一覧に戻る</a><br>
    <a href="{% url 'home' %}" class="btn btn-md btn-info" type="submit">ホームに戻る</a>
</div>
{% endblock content %}

templates/contents/item_edit/item_delete_confirm.html
{% extends 'contents/contents_base.html' %}
{% load static django_bootstrap5 humanize %}

{% block content %}
<div class="container">
    <form action='' method="POST">
        {% csrf_token %}
        <legend class="text_center space_top">削除確認画面</legend>
        <h5 class="text_center space_top">本当に削除しますか???</h5>
        <form action='' method="POST">{% csrf_token %}
          {% for item in object_item %}
          <ul>
              <li>アイテム種類：{{ item.get_item_type_display }}</li>
              <li>季節：{{ item.get_season_display }}</li>
              <li class="table-light">シーン：{{ item.get_occasion_display }}</li>
              <li class="table-light">アイテム名称：{{ item.item_name }}</li>
              <li class="table-light">アイテムカラー：{{ item.get_item_color_display }}</li>
              <li class="table-light">ブランド：{{ item.item_brand }}</li>
              <li class="table-light">購入日：{{ item.purchase_date }}</li>
              <li class="table-light">購入価格：{{ item.pricing }}</li>
              <li class="table-light">購入場所：{{ item.purchase_place }}</li>
              <li class="">メモ：{{ item.memo }}</li>
              <li class="table-light">お気に入り度：{{ item.get_favorite_level_display }}</li>
              <li class="table-light">大事さ：{{ item.get_favorite_level_display }}</li>
              </ul>
          {% endfor %}
    <input type = "submit" value = '本当に削除する'>
       </form>
<a href="{% url 'home' %}" class="btn btn-md btn-info" type="submit">ホームに戻る</a>
</div>
{% endblock content %}

templates/contents/item_edit/item_update.html
{% extends 'contents/contents_base.html' %}
{% load static django_bootstrap5 humanize extra_tags_contents %}

{% block content %}
<div class="container">
    <div class="d-flex flex-column flex-lg-row-fluid">
        <form action ='' method='POST' enctype="multipart/form-data">{% csrf_token %}
          <div class="d-flex flex-center flex-column flex-column-fluid">     
            <div class="w-md-1000px p-10 p-lg-4 mx-auto">
              <div class="mb-3 text-center">
                <h1 class="text-dark">変更内容の確認</h1>
                <h3 class="text-dark">以下の内容で更新してよいですか?</h3>
              </div>
              {% if form.errors %}
              <div class="alert alert-danger">
                <p>エラーが発生しました。</p>
                {% endif %}
                {% for field, error_list in form.errors.items %}
                <p>{{ error_list }}</p>{% endfor %}
              </div>
              <div class="row fv-row mb-5">
                <div class="col-xl-12">
                  <label for="{{ form.item_name.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.item_name.label_tag }}</label>
                  {{ form.item_name | addcss_item_create:"form-control form-control-solid" }}
                </div>
                <div class="col-xl-12">
                  <label for="{{ form.purchase_date.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.purchase_date.label_tag }}</label>
                  {{ form.purchase_date | addcss_item_create:"form-select form-select-solid" }}
                </div>
                <div class="col-xl-6">
                  <label for="{{ form.pricing.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.pricing.label_tag }}</label>
                  {{ form.pricing | addcss_item_create:"form-control form-control-solid" }}
                </div>
                <div class="col-xl-6">
                  <label for="{{ form.item_image.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.item_image.label_tag }}</label>
                  {{ form.item_image | addcss_item_create:"form-control form-control-solid" }}
                </div>
                <div class="col-xl-6">
                  <label for="{{ form.season.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.season.label_tag }}</label>
                  {% for radiobutton_season in form.season %}
                  <label class="btn btn-primary" style="margin-top: 8px; margin-bottom: 3px;">
                  {{ radiobutton_season  }}
                  </label>
                  {% endfor %}
                </div>
                <div class="col-xl-6">
                  <label for="{{ form.occasion.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.occasion.label_tag }}</label>
                  {% for radiobutton_occasion in form.occasion %}
                  <label class="btn btn-primary" style="margin-top: 8px; margin-bottom: 3px;">
                  {{ radiobutton_occasion }}
                  </label>
                  {% endfor %}
                </div>
                <div class="col-xl-6">
                  <label for="{{ form.favorite_level.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.favorite_level.label_tag }}</label>
                  {{ form.favorite_level | addcss_item_create:"form-control form-control-solid" }}
                </div>
                <div class="col-xl-6">
                  <label for="{{ form.item_importance.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.item_importance.label_tag }}</label>
                  {{ form.item_importance | addcss_item_create:"form-control form-control-solid" }}
                </div>
                <div class="col-xl-12">
                  <label for="{{ form.closet.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.closet.label_tag }}</label>
                  {{ form.closet | addcss_item_create:"form-control form-control-lg form-control-solid" }}
                </div>
                <div class="col-xl-4">
                  <label for="{{ form.item_type.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.item_type.label_tag }}</label>
                  <a href="{% url 'item_type_create' %}">新規追加する</a>
                  {{ form.item_type | addcss_item_create:"form-control form-control-lg form-control-solid" }}
                </div>
                <div class="col-xl-4">
                  <label for="{{ form.item_color.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.item_color.label_tag }}</label>
                  <a href="{% url 'item_color_create' %}">新規追加する</a>
                  {{ form.item_color | addcss_item_create:"form-control form-control-lg form-control-solid" }}
                </div>
                <div class="col-xl-4">
                  <label for="{{ form.item_brand.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.item_brand.label_tag }}</label>
                  <a href="{% url 'item_brand_create' %}">新規追加する</a>
                  {{ form.item_brand | addcss_item_create:"form-control form-control-lg form-control-solid" }}
                </div>
                <div class="col-xl-12">
                  <label for="{{ form.purchase_place.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.purchase_place.label_tag }}</label>
                  <a href="{% url 'purchase_place_create' %}">新規追加する</a>
                  {{ form.purchase_place | addcss_item_create:"form-control form-control-lg form-control-solid" }}
                </div>
                <div class="col-xl-12">
                  <label for="{{ form.memo.id_for_label }}" class="form-label fw-bolder text-dark fs-6">{{ form.memo.label_tag }}</label>
                  {{ form.memo | addcss_item_create:"form-control form-control-lg form-control-solid" }}
                </div>
              </div>
            </div>
          </div>
          <div style='text-align: center;'>
          <input type='hidden' name='action' value='confirm'>
          <input type="hidden" id="id_item_image_base64" name="item_image_base64" />
          <input type="submit" class="btn btn-danger" value='更新する'>
          <a href="{% url 'item_detail' object_item.pk %}" button class="btn btn-md btn-primary" type="submit">前のページに戻る</a>
          </div>
        </form>
       
    </div>
</div>
<script>
  function upload_img() {
    const file = this.files[0];
    const reader = new FileReader();
    const item_image_base64 = document.getElementById('id_item_image_base64');

    reader.addEventListener("load", function () {
      item_image_base64.value = reader.result;
    }, false);

    if (file) {
      reader.readAsDataURL(file);
    }
  }
  document.getElementById('id_item_image').addEventListener("change", upload_img);
</script>
{% endblock content %}